//Authentication
export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGOUT = "LOGOUT"

//Registration
export const SIGNUP_START = "SIGUP_START"
export const SIGNUP_FAILED = "SIGNUP_FAILED"

//All Advertisement
export const FETCH_ADS_START = "FETCH_ADS_START"
export const FETCH_ADS_FAILED = "FETCH_ADS_FAILED"
export const FETCH_ADS_SUCCESS = "FETCH_ADS_SUCCESS"

//Own Advertisement
export const FETCH_OWN_ADS_START = "FETCH_OWN_ADS_START"
export const FETCH_OWN_ADS_FAILED = "FETCH_OWN_ADS_FAILED"
export const FETCH_OWN_ADS_SUCCESS = "FETCH_OWN_ADS_SUCCESS"

//One adveretisement
export const FETCH_ONE_ADS_START = "FETCH_ONE_ADS_START"
export const FETCH_ONE_ADS_FAILED = "FETCH_ONE_ADS_FAILED"
export const FETCH_ONE_ADS_SUCCESS = "FETCH_ONE_ADS_SUCCESS"

//Get user info
export const FETCH_USER_INFO = "FETCH_USER_INFO_START"
export const FETCH_USER_SUCCESS = "FETCH_USER_INFO_SUCC"
export const FETCH_USER_FAILED = "FETCH_USER_INFO_FAILED"

//Projects
export const FETCH_OWN_PROJECTS_START = "FETCH_OWN_PROJECTS_START"
export const FETCH_OWN_PROJECTS_SUCCESS = "FETCH_OWN_PROJECTS_SUCCESS"
export const FETCH_OWN_PROJECTS_FAILED = "FETCH_OWN_PROJECTS_FAILED"

export const FETCH_ONE_PROJ_START = "FETCH_ONE_PROJ_START"
export const FETCH_ONE_PROJ_SUCCESS = "FETCH_ONE_PROJ_SUCCESS"
export const FETCH_ONE_PROJ_FAILED = "FETCH_ONE_PROJ_FAILED"

//Sort and filter
export const MODIFY_SORT = "MODIFY_SORT"
export const MODIFY_SORT_ORDER = "MODIFY_SORT_ORDER"
export const MODIFY_FILTER = "MODIFY_FILTER"
export const MODIFY_FILTER_RANGE = "MODIFY_FILTER_RANGE"